### PR TITLE
Bugfix: clicking on a poi in favorite pois list now takes you to poi info instead of forum

### PR DESCRIPTION
**Pull request by tberkane**

### CODE REVIEW

**Comment by aman3014** [comment]
Thanks for this fix! Since we are improving the UI now, could you also change the button in the profile to reflect that this is the favorite POIs button? For eg. the text could say "Favorite POIs" and the image could be a heart.

**Comment by tberkane** [comment]
> Thanks for this fix! Since we are improving the UI now, could you also change the button in the profile to reflect that this is the favorite POIs button? For eg. the text could say "Favorite POIs" and the image could be a heart.

Good idea, I did that

**Review by aman3014 — APPROVED** [review]

**Review by ahmedc3ca — COMMENTED** [review]
Thank you for the addition, it works as intended! Since now the favourites button in your profile take you to the poi info, maybe we should also move the favourites button in the forum activity to the poi info activity. Does this make sense?

**Review by ahmedc3ca — APPROVED** [review]
Thank you for the addition it works as intended!

**Pull request merged**
