### PR TITLE
Fix Meili Lens flicker

### PR DESCRIPTION
**Pull request by aman3014**
Improve POI detection in Meili Lens by increasing FOV and angle tolerance. I also improve the logic for lens poi update (for instance, "catching onto" a new POI is now easier if there is no current POI)

### CODE REVIEW

**Review by MarcelTorne — CHANGES_REQUESTED** [review]
Thanks for this fix Aman! Would it be possible to add a simple test that will check that everything is updated appropriately when the function is called?

**Comment by aman3014** [comment]
> Thanks for this fix Aman! Would it be possible to add a simple test that will check that everything is updated appropriately when the function is called?

How would you propose testing this? I don't see a way other than making the function public (which is a bad idea since it's not used anywhere else.

**Comment by MarcelTorne** [comment]
> > Thanks for this fix Aman! Would it be possible to add a simple test that will check that everything is updated appropriately when the function is called?
> 
> Do you have any ideas on how we could test this @MarcelTorne ? I don't see a way other than making the function public (which is a bad idea since it's not used anywhere else).

We can create an inheriting lass inside the same test file that can have a public function which will call this private function. It's not the best way but it's the only way I can think about. What do you think?

**Review by MarcelTorne — APPROVED** [review]
Discussed offline. Thanks for your work Aman!

**Review by tberkane — APPROVED** [review]
A noticeable improvement, thanks! Finding POIs with Meili Lens has never been easier.

**Pull request merged**
