### PR TITLE
Tabs: Profile, Map, and Feed

### PR DESCRIPTION
**Pull request by aman3014**
Adds three tabs to the main app and improves app navigation overall (for eg. fixing/removing up arrows lead to crashes)

### CODE REVIEW

**Review by tberkane — CHANGES_REQUESTED** [review]
This looks really cool! I just think we can remove the back button from the navigable activities.

**Comment by aman3014** [comment]
> This looks really cool! I just think we can remove the back button from the navigable activities.

I think it's nice to give the user the ability to go back and sign out. Why did you want to remove it?

**Comment by aman3014** [comment]
After our discussion on our group, I have removed the back buttons.

**Review by tberkane — APPROVED** [review]

**Review by dyxcooh — APPROVED** [review]
Well done! The three tabs UI looks really cool

**Pull request merged**
