### PR TITLE
More uniform color scheme in night mode

### PR DESCRIPTION
**Pull request by ahmedc3ca**
Hi team! Feel free to move around the activities in the dark mode theme and tell me how it looks like :). If you feel like a color doesn't fit just tell me and I'll change it.

### CODE REVIEW

**Review by MarcelTorne — CHANGES_REQUESTED** [review]
Thanks for the work Ahmed! Awesome to have night mode in the app. Do you think you could implement dark mode for the map too? I think it would be great. Here is a 5 min video that would probably help you (https://www.youtube.com/watch?v=sLZxAB1el6w)

**Review by Bwananah — APPROVED** [review]
Looks cool ! +1 for the map, but this is already enough of a feature imo

**Comment by ahmedc3ca** [comment]
Thanks for the suggestion, Marcel! I have made a new commit with this feature 👍

**Review by MarcelTorne — APPROVED** [review]
Really cool! Thanks for the work and the changes @ahmedc3ca!

**Pull request merged**
