### PR TITLE
Improve camera shutter button placement so that it doesn't block the view in landscape mode

### PR DESCRIPTION
**Pull request by tberkane**

### CODE REVIEW

**Review by MarcelTorne — COMMENTED** [review]
Thanks for this feature @tberkane! I tried to test this but on the emulator I have in my laptop when I put the phone in landscape mode everything appears distortioned, I will leave the review to someone for whom this works well.

**Review by ahmedc3ca — APPROVED** [review]
Works as intended 👍

**Review by Bwananah — CHANGES_REQUESTED** [review]
The shutter placement is correct, but now we can't take landscape photos anymore.

**Comment by tberkane** [comment]
> The shutter placement is correct, but now we can't take landscape photos anymore.

Oh yeah good catch. Now it should be good.

**Review by Bwananah — COMMENTED** [review]
I don't know, I much prefer having the button on the side in landscape mode as it was before, but still be able to take landscape photos. 
Maybe I'm the only one who prefers it that way.
What I imagined was something like Whatsapp does, which I find is the most natural.
Sorry for being picky, I just don't like having the button in the middle in landscape mode.

**Review by Bwananah — APPROVED** [review]
Perfect ! Thanks for the changes !

**Pull request merged**
